package mybatis.dao;

import java.util.List;
import mybatis.model.TreeSpecies;

public interface TreeSpeciesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE_SPECIES
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE_SPECIES
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    int insert(TreeSpecies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE_SPECIES
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    TreeSpecies selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE_SPECIES
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    List<TreeSpecies> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE_SPECIES
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    int updateByPrimaryKey(TreeSpecies record);
}