package mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class Tree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.NAME
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.PRICE
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.TREE_SPECIES_ID
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    private Integer treeSpeciesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.ID
     *
     * @return the value of PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.ID
     *
     * @param id the value for PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.NAME
     *
     * @return the value of PUBLIC.TREE.NAME
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.NAME
     *
     * @param name the value for PUBLIC.TREE.NAME
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.PRICE
     *
     * @return the value of PUBLIC.TREE.PRICE
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.PRICE
     *
     * @param price the value for PUBLIC.TREE.PRICE
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.TREE_SPECIES_ID
     *
     * @return the value of PUBLIC.TREE.TREE_SPECIES_ID
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public Integer getTreeSpeciesId() {
        return treeSpeciesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.TREE_SPECIES_ID
     *
     * @param treeSpeciesId the value for PUBLIC.TREE.TREE_SPECIES_ID
     *
     * @mbg.generated Mon May 09 12:02:09 EEST 2022
     */
    public void setTreeSpeciesId(Integer treeSpeciesId) {
        this.treeSpeciesId = treeSpeciesId;
    }

    //added manually

    private TreeSpecies treeSpecies;

    private List<Myorder> orders = new ArrayList<>();

    public List<Myorder> getOrders() {
        return orders;
    }

    public void setOrders(List<Myorder> orders) {
        this.orders = orders;
    }


    public TreeSpecies getTreeSpecies() {
        return treeSpecies;
    }

    public void setTreeSpecies(TreeSpecies treeSpecies) {
        this.treeSpecies = treeSpecies;
    }



}